language: csharp
mono: none
dotnet: 2.1.502
script:
 - dotnet restore
 - dotnet build
 - cd VehicleTracking.Vehicle.API.UnitTesting && dotnet test
 - cd ../VehicleTracking.Customer.API.UnitTest && dotnet test
 - cd ../VehicleTracking.VehicleConnection.API.UnitTesting && dotnet test
 - cd ../VehicleTracking.Customer.API.IntegrationTesting && dotnet test
 - cd ../VehicleTracking.Vehicle.API.IntegrationTesting && dotnet test
 - cd ../VehicleTracking.VehicleConnection.API.IntegrationTesting && dotnet test
